services:
  # Nginx Proxy Manager
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '40080:80'
      - '40443:443'
      - '40081:81'
    volumes:
      - ./nginx/data:/data
      - ./nginx/letsencrypt:/etc/letsencrypt
    networks:
      - proxy-network
    environment:
      - TZ=America/Argentina/Buenos_Aires

  # Jellyfin Media Server
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    networks:
      - proxy-network
    ports:
      - 8096:8096
    volumes:
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
      - /media/guido/HDD3:/media
    environment:
      - TZ=America/Argentina/Buenos_Aires

  # Sonarr
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    networks:
      - proxy-network
    ports:
      - 8989:8989
    volumes:
      - ./sonarr/config:/config
      - /media/guido/HDD3/media:/media
      - ./downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    networks:
      - proxy-network
    ports:
      - "9696:9696"
    environment:
      - PUID=1000
      - PGID=1000 
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - ./prowlarr/config:/config

  deluge:
    image: linuxserver/deluge:latest
    container_name: deluge
    restart: unless-stopped
    networks:
      - proxy-network
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - ./deluge/config:/config
      - ./downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires

  # Bazarr - Subtitle Management
  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    networks:
      - proxy-network
    ports:
      - 6767:6767
    volumes:
      - ./bazarr/config:/config
      - /media/guido/HDD3/media:/media
      - ./downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires

# Home Assistant
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    networks:
      - proxy-network
    ports:
      - 8123:8123
    volumes:
      - ./homeassistant/data/homeassistant:/config
    privileged: true # Required for some integrations
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    environment:
      - TZ=America/Argentina/Buenos_Aires

networks:
  proxy-network:
    driver: bridge